### ISSUE TITLE
Rime部署時出現錯誤

### ISSUE THREAD

**Issue by Pygmalion6636** [rime/home#114] opened 2016-10-12 04:35 UTC
/tmp/rime.ibus.ERROR 出錯信息如下：
Log file created at: 2016/10/12 12:23:12
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1012 12:23:12.978267  8285 deployment_tasks.cc:241] source file 'stroke.dict.yaml' does not exist.
E1012 12:23:12.978441  8285 dict_compiler.cc:87] neither stroke.dict.yaml nor stroke.table.bin exists.
E1012 12:23:12.978454  8285 deployment_tasks.cc:300] dictionary 'stroke' failed to compile.
E1012 12:27:12.087173  8582 deployment_tasks.cc:241] source file 'stroke.dict.yaml' does not exist.
E1012 12:27:12.087231  8582 dict_compiler.cc:87] neither stroke.dict.yaml nor stroke.table.bin exists.
E1012 12:27:12.087242  8582 deployment_tasks.cc:300] dictionary 'stroke' failed to compile.

**Comment by lotem** [comment] 2016-10-14 03:21
Duplicate of https://github.com/rime/ibus-rime/issues/17

**Closed by lotem** 2016-10-14 03:21 UTC
